services:
  node:
    container_name: node
    image: ipfs/kubo:latest
    privileged: true
    ports:
      - "4001:4001" # IPFS swarm (TCP)
      - "4001:4001/udp" # IPFS swarm (UDP)
      - "127.0.0.1:5001:5001" # IPFS API
    volumes:
      - ./scripts/rm-stale-lockfile.sh:/container-init.d/rm-stale-lockfile.sh:ro
      - ${STORAGE_PATH_IPFS}:/data/ipfs
      - ${STORAGE_PATH_EXPORT}:/export
    environment:
      - IPFS_PROFILE=server
    restart: always
    healthcheck:
      test: ["CMD", "ipfs", "id"]
      interval: 30s
      timeout: 10s
      retries: 3
  pinner:
    container_name: pinner
    build:
      context: ./pinner
      dockerfile: Dockerfile
      args:
        PRIVATE_KEY: ${PRIVATE_KEY}
        CHAIN_WS_URL: ${NODE_PROVIDER_URL}
    depends_on:
      node:
        condition: service_healthy
    restart: always
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    group_add:
      - ${DOCKER_GID}
    privileged: true
    env_file: .env
    restart: always
